import PaddingContainer from '@/components/Layout/PaddingContainer';
import '../globals.css';
export const metadata = {
  title: 'Dipalo Ventures',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-black h-screen flex justify-center items-center">
        <PaddingContainer>{children}</PaddingContainer>
      </body>
    </html>
  );
}
