export const mainTeam = [
  {
    id: 1,
    name: 'RAFIQ AHMED',
    image: '/assets/about-us/rafiq.png',
    designation: 'Managing Partner',
    linkedinLink: 'https://www.linkedin.com/in/ahmedrafiq/',
    bio: '<p>Rafiq is the Founding Managing Director at Dipalo Ventures. As a serial entrepreneur and investor, Rafiq has over three decades of experience in innovation, user experience design, product development, management consulting, and early-stage ventures. <br/> <br/> His investment focus areas include climate, industrial, manufacturing, and medical devices. Rafiq’s angel investment portfolio has a 29.23% IRR, 2.33x MOIC with 1 unicorn and 5 exits. He co-founded the interactive storytelling platform Demibooks and exited to EDC (NASDAQ: EDUC). He is a Limited Partner in a number of Venture Capital Funds. Rafiq’s prior work included Motorola Mobility, Publicis Sapient Fannie Mae, and PwC. <br /> <br/>Rafiq studied Computer Science and received an MBA from Virginia Tech and a BS in Electrical Engineering from West Virginia Wesleyan.</p>',
    priorInvestments: [
      {
        id: 1,
        logo: '/assets/prior-invest/rafiq/factor.webp',
        name: 'Factor',
        status: 'Exit',
        link: 'https://www.factor75.com/',
      },
      {
        id: 2,
        logo: '/assets/prior-invest/rafiq/avail.jpg',
        name: 'Avail',
        status: 'Exit',
        link: 'https://www.realtor.com/',
      },
      {
        id: 3,
        logo: '/assets/prior-invest/rafiq/jiobit.png',
        name: 'Jiobit',
        status: 'Exit',
        link: 'https://www.jiobit.com/',
      },
      {
        id: 4,
        logo: '/assets/prior-invest/rafiq/kin.svg',
        name: 'Kin',
        status: 'Ongoing',
        link: 'https://www.kin.com/',
      },
      {
        id: 5,
        logo: '/assets/prior-invest/rafiq/demibooks.jpeg',
        name: 'DemiBook',
        status: 'Exit',
        link: 'https://www.edcpub.com/',
      },
      {
        id: 6,
        logo: '/assets/prior-invest/rafiq/draftbit.png',
        name: 'Draftbit',
        status: 'Ongoing',
        link: 'https://draftbit.com/',
      },
      {
        id: 7,
        logo: '/assets/prior-invest/rafiq/servicechai.webp',
        name: 'ServiceChai',
        status: 'Ongoing',
        link: 'https://servicechai.com/',
      },
      {
        id: 8,
        logo: '/assets/prior-invest/rafiq/servicechai.webp',
        name: 'Truss',
        status: 'Exit',
        link: 'https://servicechai.com/',
      },
      {
        id: 9,
        logo: '/assets/prior-invest/rafiq/mitro.png',
        name: 'Mitro',
        status: 'Ongoing',
        link: 'https://mitro.io/',
      },
      {
        id: 10,
        logo: '/assets/prior-invest/rafiq/quicklly.png',
        name: 'Quicklly',
        status: 'Ongoing',
        link: 'https://www.quicklly.com/',
      },
      {
        id: 11,
        logo: '/assets/prior-invest/rafiq/quicklly.png',
        name: 'Zantrik',
        status: 'Ongoing',
        link: 'https://www.zantrik.com/',
      },
      {
        id: 12,
        logo: '/assets/prior-invest/rafiq/quicklly.png',
        name: 'Jolpi',
        status: 'Inactive',
        link: '#',
      },
      {
        id: 13,
        logo: '/assets/prior-invest/rafiq/ballotready.svg',
        name: 'Jolpi',
        status: 'Ongoing',
        link: 'https://www.ballotready.org/',
      },
    ],
  },
  {
    id: 2,
    name: 'DR. LAUREN BIGELOW',
    image: '/assets/about-us/lauren.png',
    designation: 'Managing Partner',
    linkedinLink: 'https://www.linkedin.com/in/laurenbigelow/',
    bio: '<p>Lauren is a Managing Partner at Dipalo Ventures. She works to raise and effectively deploy the fund’s capital into top-flight companies. She sources high-quality startups, assists with the Dipalo Ventures Residency, and performs due diligence to ensure a high-quality portfolio. <br /><br/> Lauren has over 20 years of startup investment, capacity building, and mentorship. She is an active LP, serial entrepreneur, and angel investor. Her focus areas include energy, innovative materials, IT, Fintech, and B2C fields. Previously, Lauren screened thousands of high-growth technology companies in her role as the Founding Managing Director of the Cleantech Group and Executive Director at Accelerate Michigan. She is also an active board member of the Michigan Department of Treasury’s Board of Financial Authority.  <br /><br/> Lauren received her MA and Ph.D. from Northwestern University and her BA from the University of Michigan.</p>',
  },
  {
    id: 3,
    name: 'MITUL PATEL',
    image: '/assets/about-us/mitul-patel.png',
    designation: 'Venture Partner',
    linkedinLink: 'https://www.linkedin.com/in/mrpatel624/',
    bio: '<p>Mitul works as a Venture Partner for Dipalo Ventures. He leads technical due diligence and the Dipalo Ventures Residency for Fund I. <br/><br/> Mitul is the Founder and CEO of M.P. Consulting (MPC) and contractor manufacturer AMC. He has more than 15 years of expertise designing consumer electronics for Motorola Mobility, Cuff., and MPC. He has worked on projects including wearables, smart homes, smartphones, and industrial sensors and has filed more than ten U.S. Patents. In addition to his work at MPC, Mitul has made it his life’s mission to establish his son’s legacy with an initiative to benefit Maternal Fetal Medicine and Fertility with an intense focus on technology development, data analytics, and worldwide causes. Women’s Health is the centerpiece for Mitul’s entire operation from MPC to AMC and his son’s namesake foundation: The Aarush M. Patel Foundation.  <br/><br/> Mitul received a BS in Computer Engineering from the University of Illinois Urbana-Champaign and an MS in Computer and Electrical Engineering from the Illinois Institute of Technology.</p>',
  },
  {
    id: 4,
    name: 'LARRY HAYWARD',
    image: '/assets/about-us/larry.png',
    designation: 'Venture Partner',
    linkedinLink: 'https://www.linkedin.com/in/laurence-hayward-a33a57/',
    bio: '<p>Larry is a Venture Partner at Dipalo Ventures. Larry invests in researchers and engineers developing game-changing technology. Recent examples include microneedle medication delivery systems, self-healing coatings, tankless water, air heating, and wireless power technologies. <br/><br/> Larry is also a Partner and Co-founder of hard tech VC Fund Independence Equity, which focuses on efficient resource utilization in early-stage investments. He is a Co-founder of Cornerstone Angels, one of Chicago’s earliest angel networks. Since 2003, he has provided startups investment banking, governance, and management support through VentureLab. His prior work also included Arthur Andersen’s small business advisory division. He is a board member of the EcoMyths alliance and the executive-in-residence at the Chicagoland Entrepreneurial Center. <br/><br/>  Larry received an MBA in Marketing and Finance and a BS in Psychology and Operational Behavior from the University of Illinois Urbana-Champaign.</p>',
  },
  {
    id: 5,
    name: 'MONIKA RAZDAN',
    image: '/assets/about-us/monika.png',
    designation: 'Analyst',
    linkedinLink: 'https://www.linkedin.com/in/monarazdan/',
    bio: '<p>Monika is an Analyst at Dipalo Ventures, and works across Platform Support, Investor Relations, Deal Sourcing, and Marketing.    <br/>   <br/> Monika is a member of the Fall 2022 cohort of Chicago Venture Fellows by Chicago:Blend. She is a Founder of Mental Polaroids, a startup dedicated to raising mental health awareness and normalizing it in our community. <br/>   <br/> Monika received an MS in Marketing Analytics from Illinois Tech’s Stuart School of Business and a BS in Computer Science from Punjab Technical University (India).</p>',
  },
  {
    id: 6,
    name: 'OLUSEYI FASORANTI',
    image: '/assets/about-us/seyi.png',
    designation: 'MBA Associate',
    linkedinLink: 'https://www.linkedin.com/in/laurence-hayward-a33a57/',
    bio: '<p>Seyi is a second-year University of Chicago Booth student interested in the intersection of Climate Tech and Hard Tech. He has experience in Investment Banking, Fixed Income, and Semiconductor Engineering. he did his PhD in Chemistry and Material Science at Princeton University, an MSc in Chemical Engineering at the University of Manchester, and a BS in Biochemistry at Georgetown University.    <br/>   <br/>Seyi is very excited at the opportunity to develop POVs and marketing research at the Dipalo Venture.</p>',
  },
];
