import { TCompany } from '@/components/types';

export const companies = [
  {
    name: 'Azumo',
    category: 'Climate Tech',
    state: 'Illinois',
    stage: 'Series B',
    logo: '/assets/logo/azumo.jpg',
    link: '#',
  },
  {
    name: 'Mito Materials',
    category: 'Climate Tech',
    state: 'Indiana',
    stage: 'N/A',
    logo: '/assets/logo/mito.png',
    link: '#',
  },
  {
    name: 'Ascent',
    category: 'Connected Device',
    state: 'Illinois',
    stage: 'Seed',
    logo: '/assets/logo/asent.png',
    link: '#',
  },
  {
    name: 'Grind',
    category: 'Connected Device',
    state: 'Texas',
    stage: 'Pre-seed',
    logo: '/assets/logo/grind.png',
    link: '#',
  },
  {
    name: 'Throne Labs',
    category: 'Connected Device',
    state: 'Virginia',
    stage: 'Seed',
    logo: '/assets/logo/throne.png',
    link: '#',
  },
  {
    name: 'Immersed',
    category: 'Connected Device',
    state: 'Texas',
    stage: 'Seed',
    logo: '/assets/logo/immersed.png',
    link: '#',
  },
  {
    name: 'Jiobit',
    category: 'Connected Device',
    state: 'Illinois',
    stage: 'Seed',
    logo: '/assets/logo/jiobit.png',
    link: '#',
  },
  {
    name: 'WasteWizer',
    category: 'Industrial and Advanced Manufacturing',
    state: 'Virginia',
    stage: 'Seed',
    logo: '/assets/logo/watewizer.png',
    link: '#',
  },
  {
    name: 'NuCurrent',
    category: 'Industrial and Advanced Manufacturing',
    state: 'Illinois',
    stage: 'Series B',
    logo: '/assets/logo/nucurrent.png',
    link: '#',
  },
  {
    name: 'Vumo',
    category: 'Mobility',
    state: 'Illinois',
    stage: 'Seed',
    logo: '/assets/logo/vumo.jpg',
    link: '#',
  },
  {
    name: 'NovaScan',
    category: 'Med Tech',
    state: 'Illinois',
    stage: 'Series B',
    logo: '/assets/logo/novascan.png',
    link: '#',
  },
  {
    name: 'Amulet',
    category: 'Food and Agriculture',
    state: 'Wisconsin',
    stage: 'Series A',
    logo: '/assets/logo/amulet.png',
    link: '#',
  },
  {
    name: 'Flora',
    category: 'Food and Agriculture',
    state: 'Illinois',
    stage: 'Seed',
    logo: '/assets/logo/flora.jpg',
    link: '#',
  },
  {
    name: 'Zenblen',
    category: 'Food and Agriculture',
    state: 'Illinois',
    stage: 'Seed',
    logo: '/assets/logo/zenblen.png',
    link: '#',
  },
];
